;
; File generated by cc65 v 2.19 - Git f54780c
;
	.fopt		compiler,"cc65 v 2.19 - Git f54780c"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_SCR_DATA
	.export		_SCR_CTRL
	.export		_putchar
	.export		_hello
	.export		_msg
	.export		_main

.segment	"DATA"

_SCR_DATA:
	.word	$c00a
_SCR_CTRL:
	.word	$c00b
_msg:
	.addr	S0001

.segment	"RODATA"

S0001:
	.byte	$48,$65,$6C,$6C,$6F,$20,$57,$6F,$72,$6C,$64,$21,$0A,$00

; ---------------------------------------------------------------
; void __near__ putchar (char c)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_putchar: near

.segment	"CODE"

;
; void putchar(char c){
;
	jsr     pusha
;
; *SCR_DATA = c;
;
	lda     _SCR_DATA+1
	sta     ptr1+1
	lda     _SCR_DATA
	sta     ptr1
	ldy     #$00
	lda     (c_sp),y
	sta     (ptr1),y
;
; *SCR_CTRL = SCR_WRITE;
;
	lda     _SCR_CTRL+1
	sta     ptr1+1
	lda     _SCR_CTRL
	sta     ptr1
	lda     #$01
	sta     (ptr1),y
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ hello (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hello: near

.segment	"CODE"

;
; putchar('H');
;
	lda     #$48
	jsr     _putchar
;
; putchar('e');
;
	lda     #$65
	jsr     _putchar
;
; putchar('l');
;
	lda     #$6C
	jsr     _putchar
;
; putchar('l');
;
	lda     #$6C
	jsr     _putchar
;
; putchar('o');
;
	lda     #$6F
	jsr     _putchar
;
; putchar(' ');
;
	lda     #$20
	jsr     _putchar
;
; putchar('W');
;
	lda     #$57
	jsr     _putchar
;
; putchar('o');
;
	lda     #$6F
	jsr     _putchar
;
; putchar('r');
;
	lda     #$72
	jsr     _putchar
;
; putchar('l');
;
	lda     #$6C
	jsr     _putchar
;
; putchar('d');
;
	lda     #$64
	jsr     _putchar
;
; putchar('!');
;
	lda     #$21
	jsr     _putchar
;
; putchar('\n');
;
	lda     #$0A
	jmp     _putchar

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; hello();
;
	jsr     _hello
;
; for (;;) {
;
L0004:	jmp     L0004

.endproc

