;
; File generated by cc65 v 2.18 - Git 01905a8
;
	.fopt		compiler,"cc65 v 2.18 - Git 01905a8"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	_start
	.export		_main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"BSS"

L0002:
	.res	2,$00
L0004:
	.res	2,$00

.segment	"CODE"

;
; volatile unsigned char *SCR_DATA = (unsigned char *)MMIO_SCR_DATA;
;
	ldx     #$C0
	lda     #$0A
	sta     L0002
	stx     L0002+1
;
; volatile unsigned char *SCR_CTRL = (unsigned char *)MMIO_SCR_CTRL;
;
	lda     #$0B
	sta     L0004
	stx     L0004+1
;
; *SCR_DATA = 'H';
;
	lda     L0002+1
	sta     ptr1+1
	lda     L0002
	sta     ptr1
	lda     #$48
	ldy     #$00
	sta     (ptr1),y
;
; *SCR_CTRL = SCR_WRITE;
;
	lda     L0004+1
	sta     ptr1+1
	lda     L0004
	sta     ptr1
	lda     #$01
	sta     (ptr1),y
;
; *SCR_DATA = 'I';
;
	lda     L0002+1
	sta     ptr1+1
	lda     L0002
	sta     ptr1
	lda     #$49
	sta     (ptr1),y
;
; *SCR_CTRL = SCR_WRITE;
;
	lda     L0004+1
	sta     ptr1+1
	lda     L0004
	sta     ptr1
	lda     #$01
	sta     (ptr1),y
;
; for (;;) {
;
L0010:	jmp     L0010

.endproc

